### PR TITLE
Make `obt test --debug` watch for changes and rebuild tests. 

### PR DESCRIPTION
**Pull request by notlee**
Re-running the test command manually to build test assets,
which would also mean restarting karma, was very painful
whilst working on this:
Financial-Times/o-tracking#333

### CODE REVIEW

**Comment by notlee** [comment]
I'll port this to the next major when/if it's approved

**Comment by JakeChampion** [comment]
@notlee did you mean to change the npm-shrinkwrap.json file to be in the older lockfile format?

**Review by JakeChampion — APPROVED** [review]

**Comment by notlee** [comment]
@JakeChampion I left it in intentionally. Locally I'm running 6.14.11 which updated it on `npm install`. I figure since we have `"npm": ">= 6.0.0"` configured for this version of obt it'd be better leaving it at v1

**Comment by origamiserviceuser** [comment]
:tada: This PR is included in version v10.9.0 :tada:

**Pull request merged**
