### PR TITLE
Add config option to make JSHint exit with code 1 when linting errors a...

### PR DESCRIPTION
**Pull request by robin-marr-ft**
...re found @AlbertoElias @matthew-andrews 

This was buggin me too so I've added a config option to allow this.

### CODE REVIEW

**Comment by robin-marr-ft** [comment]
when in dev it's nice to not have it exit so verification continues and you
see any lintspaces errors too, we could make it default true and leave the
option so people can chose.

On 9 January 2015 at 09:36, Alberto Elias <notifications@github.com> wrote:

> This is great, but I don't think it should be a config option, it should
> just be like that
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/origami-build-tools/pull/184#issuecomment-69312301>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by AlbertoElias** [comment]
We need to find a way to make sure it works similar to how it does if you run console commands (like we used to do) where it would run the different verify tasks, and if at least one failed, it would fail the whole thing but it would run all of them. scsslint and lintspaces also need to make sure they fail. Do you have any suggestions on how to do this?

**Comment by robin-marr-ft** [comment]
I think this is possible but don't have time today, I'll take a look Monday
if that's ok?

On 9 January 2015 at 13:20, Alberto Elias <notifications@github.com> wrote:

> We need to find a way to make sure it works similar to how it does if you
> run console commands (like we used to do) where it would run the different
> verify tasks, and if at least one failed, it would fail the whole thing but
> it would run all of them. scsslint and lintspaces also need to make sure
> they fail. Do you have any suggestions on how to do this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/origami-build-tools/pull/184#issuecomment-69333032>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by AlbertoElias** [comment]
Sure, I need to get this sorted out for the testing branch as well and will look into it as soon as I finish some o-overlay issues

**Comment by AlbertoElias** [comment]
This is fixed in the testing branch which will be pushed by Friday

**Pull request closed without merging**
