### PR TITLE
Try Node 5

### PR DESCRIPTION
**Pull request by matthew-andrews**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
oops

**Comment by matthew-andrews** [comment]
@AlbertoElias can we run the tests on Node 5 too :-)

**Comment by AlbertoElias** [comment]
That will only run obt stuff in node 5. Is that what you mean?

**Comment by matthew-andrews** [comment]
no it should run the test suite in both 4 and 5

**Comment by AlbertoElias** [comment]
What test suite? What I'm saying is that this will only run OBT tests in node 5 in travis, not all origami modules

**Comment by matthew-andrews** [comment]
Yeah… that's fine I think.  We are starting to think about porting our apps to Node 5…  and we wanted to make sure that the build tools work in Node 5.

**Comment by AlbertoElias** [comment]
Ok, fine

**Pull request merged**
