### PR TITLE
make obt init call npm init origami-component

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by notlee** [comment]
Nice! We can delete all the stuff in ` lib/tasks/boilerplate`

**Comment by notlee** [comment]
And all of these 😄 https://github.com/Financial-Times/origami-build-tools/pull/755/commits/bbbd520a7895d06ec31f7dfd57f45f79864e0f00#diff-f4ff27affcdccb91e156216ec206fa9cL11-L34

**Comment by notlee** [comment]
There's an integration test that runs `obt  init` then checks building, demos, and linting doesn't error. That'll fail as the cli is interactive now. Maybe we can delete that test in favour of a unit test which checks create-origami-component is called? Since create-origami-component is responsible for creating a new component now

**Comment by JakeChampion** [comment]
I'm fixing all these things :-)

**Comment by chee** [comment]
ha! fantastic

**Comment by chee** [comment]
yay! this is fantastic

**Pull request merged**
