### PR TITLE
Remove production option as this tool is not used for production builds

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by notlee** [comment]
Wasn't the plan to improve component authoring tools within obt but keep it for building projects too untill we eventually break out oat? We use obt to build the reigstry and during the intro to origami workshop -- unsure how useful a revamped obt would be for our users building projects but it comes up from time to time

**Comment by JakeChampion** [comment]
What commands are used by products? Is it only `obt build`? If so, that can be replaced by `oax` and `swc` for JS files and `sass` for the Sass files.

**Comment by notlee** [comment]
Just build, with the watch flag also

**Comment by chee** [comment]
i'm not sure about removing build in v10.

maybe we should explore alternatives for the workshop first, and for the apps that still use it

**Comment by JakeChampion** [comment]
Here's an alternative for an Origami application --> https://github.com/Financial-Times/origami-registry-ui/pull/271

**Comment by notlee** [comment]
Agree with @chee! That example looks good Jake. If we wrap that up into a friendly little cli, I'd be happy to remove build in v10 :)

**Comment by notlee** [comment]
Some tests need updating to remove sourcemap expectations

**Pull request merged**
