### PR TITLE
Add a license as per the FT open sources guidelines

### PR DESCRIPTION
**Pull request by robin-marr-ft**

### CODE REVIEW

**Comment by kaelig** [comment]
Nice one! Should it be in the README or should we just have a LICENSE.md file?

**Comment by AlbertoElias** [comment]
I think we should have it in a LICENSE.md file

**Comment by matthew-andrews** [comment]
https://docs.google.com/a/ft.com/document/d/1pI-qI3BrO5edFYdHcoDCH9wVbfbFvroclxSEtkXwpCw/edit?usp=drive_web

guidance is clear… no license.md files…

**Comment by AlbertoElias** [comment]
Right, could we add it to the end of the readme then?

**Comment by robin-marr-ft** [comment]
I've moved it to the bottom of the readme and merged master

**Pull request merged**
