### PR TITLE
checking for semver compatibility rather than less than-ness

### PR DESCRIPTION
**Pull request by wheresrhys**
@AlbertoElias @kaelig

### CODE REVIEW

**Comment by AlbertoElias** [comment]
Doesn't seem to work, didn't pass Travis

**Comment by wheresrhys** [comment]
@alberto fixed it, though maybe in a slightly inelegant way

**Comment by AlbertoElias** [comment]
Why not just change the versions on the versions object?

**Comment by triblondon** [comment]
I would guess Rhys has a later version already installed and wants to avoid obt downgrading it.

**Comment by wheresrhys** [comment]
And the opposite too - I want to avoid upgrading every time there is a patch release. More than likely these include fixes for edge cases that won't affect me. If there is an important fix that everyone should be forced to pick up obt should update the semvers here.

**Comment by wheresrhys** [comment]
Incidentally if either of you know of a way of installing a gem using a semver range I'll happily substitute that method in here. A cursory search didn't turn anything up, but I'd be surprised if there isn't a proper semver implementation built into gem

**Comment by AlbertoElias** [comment]
I'll discuss this with Rhys on Thursday

**Comment by wheresrhys** [comment]
nudge @AlbertoElias @triblondon @kaelig Who's in OSB next so we can discuss and get it merged?

**Comment by AlbertoElias** [comment]
@wheresrhys Oh yes, let's do it this Friday

**Comment by wheresrhys** [comment]
:+1::+1:


On 24 March 2015 at 11:39, Alberto Elias <notifications@github.com> wrote:

> Merged #209
> <https://github.com/Financial-Times/origami-build-tools/pull/209>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/origami-build-tools/pull/209#event-263399119>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by AlbertoElias** [comment]
I'm going ot change it though so the minimum Sass is 3.4, and scss-lint is 0.28, to avoid issues, I think we should set 3.4 as the baseline

**Comment by wheresrhys** [comment]
Ah yes, sorry, I missed that change. origami must've switched to 3.4 since my original PR

**Pull request merged**
