### PR TITLE
Adding compress option

### PR DESCRIPTION
**Pull request by aintgoin2goa**
For next we want to have sourcemaps in production - this option will make this possible as then we can perform the minification ourselves.

You can specify `true` `false` or object ie: `{js:false,sass:true}`

If the compress option is not specified it falls back to the default behaviour.

### CODE REVIEW

**Comment by AlbertoElias** [comment]
Is this an improved version of #171 ?

**Comment by aintgoin2goa** [comment]
No, that option just generated sourcemaps - this one sets whether or not the output is compressed, overriding the env setting.

**Comment by AlbertoElias** [comment]
but those two are what the development environment supports, why not just
use that?

*Alberto Elias*
Developer
FT Technology

+44 (0)74 75765609
Number One Southwark Bridge, London SE1 9HL


<https://www.facebook.com/financialtimes> <https://twitter.com/FT>
<http://www.linkedin.com/company/financial-times>
<https://plus.google.com/+FinancialTimes/posts>
<http://www.youtube.com/user/FinancialTimesVideos>


On 7 January 2015 at 17:09, Paul Wilson <notifications@github.com> wrote:

> No, that option just generated sourcemaps - this one sets whether or not
> the output is compressed, overriding the env setting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/origami-build-tools/pull/175#issuecomment-69054548>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by aintgoin2goa** [comment]
Yeah, that is a fair point.  It just seems odd to set env to 'development' for a production build, which is what I'd have to do.  Also, I think that it would be clearer to use explicit options for these behaviours.

I guess, it's just a matter of opinion, though - I can just use 'development' to achieve what I need.

**Comment by AlbertoElias** [comment]
I think we should either have one or the other. @matthew-andrews @kaelig @triblondon What do you think?

**Comment by kaelig** [comment]
I'm in favour of having the ability to toggle sourcemaps generation independently from the environment, with sensible defaults.

**Comment by AlbertoElias** [comment]
Then should we look at deprecating the environment config option in favour of two separate compress and sourcemaps options which are basically what the environment option toggles

**Comment by triblondon** [comment]
Fine with me.

**Pull request merged**
