### PR TITLE
Better sudo explanation

### LINKED ISSUE #305: Find safer instructions for installing OBT globally
image

Look, even I know it's bad to tell origami users (who may not be power users) to blindly use sudo. Sure it's okay for OBT, but the implication is it's safe to use sudo to install any old node package. And it really, really isn't. Right?

http://bfy.tw/1hzs

### PR DESCRIPTION
**Pull request by AlbertoElias**
Fixes #305

### CODE REVIEW

**Comment by adambraimbridge** [comment]
Thanks for looking into this. Is there a nice URL you can add to the message to point to the npm setup instructions? 

image

**Comment by AlbertoElias** [comment]
@adambraimbridge how about now?

**Comment by adambraimbridge** [comment]
Unfortunately that guide just has more instructions using sudo, so now it's like stepping out of the frying pan into the fire :) 

I guess the problem's bigger than I thought. _Looks like it's impossible for a n00b to get up and running to develop new sites based on origami without using sudo._ So the implication that it's safe to use sudo is still there. 

Maybe the only way to make it better is to keep stressing to n00bs how important it is to be careful when using sudo ...

Anyway, :+1:  for this PR :)

**Comment by AlbertoElias** [comment]
Actually, we only recommend sudo after offering a way to configure your permissions so you don't need sudo for both npm and Ruby Gems. There is one place where we still only suggest sudo, and I'll update that right away

**Comment by AlbertoElias** [comment]
I've updated the troubleshoot guide removing that use of sudo, and adding a notice about the risk of using sudo

**Comment by adambraimbridge** [comment]
Excellent. Thanks again Alberto :+1:

**Comment by AlbertoElias** [comment]
Thank you for reporting!

**Pull request merged**
